# Generated by Django 4.1.3 on 2022-11-09 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('identificador', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('fechaRegistro', models.DateField(auto_now_add=True)),
                ('cantidadRegistrada', models.PositiveIntegerField()),
                ('cantidadActual', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBiblioteca.persona')),
                ('idMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBiblioteca.material')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='idRol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBiblioteca.rol'),
        ),
        migrations.CreateModel(
            name='MaterialPrestado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBiblioteca.persona')),
                ('idMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBiblioteca.material')),
            ],
        ),
    ]
