# Generated by Django 4.1.3 on 2022-11-05 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('identificador', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('fechaRegistro', models.DateField(auto_now_add=True)),
                ('cantidadRegistrada', models.IntegerField()),
                ('cantidadActual', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('identificador', models.IntegerField(primary_key=True, serialize=False)),
                ('prestado', models.BooleanField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBiblioteca.persona')),
            ],
        ),
    ]
