# Generated by Django 4.1.3 on 2022-11-09 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='estado',
            new_name='movimiento',
        ),
    ]
