# Generated by Django 4.1.3 on 2022-11-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cantidadActual',
            field=models.IntegerField(verbose_name=models.IntegerField()),
        ),
    ]
