# Generated by Django 4.1.3 on 2022-11-05 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBiblioteca.persona')),
                ('idMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBiblioteca.material')),
            ],
        ),
    ]
