# Generated by Django 4.1.3 on 2022-11-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblioteca', '0002_alter_material_cantidadactual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cantidadActual',
            field=models.IntegerField(default=models.IntegerField()),
        ),
    ]
