# Generated by Django 4.1.3 on 2022-11-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblioteca', '0002_materialp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialP',
            new_name='MaterialPrestado',
        ),
    ]
