# Generated by Django 4.1.3 on 2022-11-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblioteca', '0003_alter_material_cantidadactual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cantidadActual',
            field=models.IntegerField(),
        ),
    ]
